### ISSUE TITLE
Add support to 2+ Connect 

### ISSUE THREAD

**Issue by jLynx** [jellespijker/home-assistant-ultimaker#13]
Hi, it would be awesome if you could add support for the Ultimaker 2+ Connect.

I have one, so happy to test anything.

**Comment by jellespijker** [comment]
Hi @jLynx 

The plan is to add support for the Digital Factory, which would also include the UM2+ Connect. See issue #5 .

Thanks for the offer and I certainly hope you check how it works on your setup (and give feedback), but for the initial setup it wouldn't be necesarry. I work for Ultimaker so I have a couple of UM2+ Connect printers available to me ;-)

**Comment by jLynx** [comment]
Awesome. I assume we will still be able to have cameras? I ask as I have "modded" mine to have a camera. It basically uses an OrangePi and  a modded laptop webcam 
![received_1965114973654029](https://user-images.githubusercontent.com/4393979/126695392-d1079cf2-cfa9-495e-b716-9f611294c15d.jpeg)

**Comment by jellespijker** [comment]
The UM2+ connect doesn't have a local API. So sensor readouts will be limited even with the planned Digitial Factory extension.
Nice mod btw, I will share it with the UM2+ connect team, they will appreciate that.

Support for cameras is baked into Home Assistant, check out the **camera** integration: https://www.home-assistant.io/integrations/camera/ 
Which is basically what I use myself:
```json
camera:
  - platform: generic
    still_image_url: http://ip_adress:8080/?action=snapshot
    framerate: 4
```

I will close this issue in favor of #5 since that ticket will automatically implement your request.
